import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/store/ReduxProvider';
import NetworkErrorWrapper from '@/components/NetworkError/NetworkErrorWrapper';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${montserrat.variable}`}>
      <ReduxProvider>
        <body>
          <NetworkErrorWrapper>{children} </NetworkErrorWrapper>
        </body>
      </ReduxProvider>
    </html>
  );
}
